# Generated by Django 3.1.4 on 2020-12-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('RoomRental', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='room_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='content',
        ),
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(default='Unkown', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='movein_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
