# Generated by Django 3.1.4 on 2020-12-15 15:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('RoomRental', '0004_auto_20201216_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
    ]
