# Generated by Django 3.1.4 on 2020-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRental', '0006_auto_20201216_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
