# Generated by Django 3.1.4 on 2020-12-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRental', '0008_auto_20201216_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
