# Generated by Django 3.1.4 on 2021-01-13 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRental', '0010_auto_20201231_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='default',
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
