# Generated by Django 3.1.4 on 2021-01-14 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomRental', '0012_auto_20210114_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='movein_date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 14)),
        ),
    ]
